version: '3.8'

services:
  web:
    restart: always
    command: npm start
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    stdin_open: true
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    env_file:
      - .env
